services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env 
    volumes:
      - ./.:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - network-backend

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    networks:
      - network-backend
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  network-backend: